<?php

$projects = [
    [
        'title' => 'Artífices TV',
        'slug' => 'artifices-tv',
        'client' => 'Artífices TV',
        'category' => 'Streaming & Media',
        'project_date' => '2024-06-05',
        'summary' => 'Plataforma web de streaming, conectividad y contenidos audiovisuales con diseño de vanguardia y experiencia inmersiva.',
        'full_description' => 'Desarrollo de sitio web corporativo elaborado en WordPress con Elementor para Artífices TV (artifices.tv). Plataforma enfocada en servicios de transmisión en vivo de alta definición, conectividad satelital y coberturas de eventos masivos creada desde la idea y requerimientos del cliente.',
        'status' => 'Finalizado',
        'project_url' => 'https://artifices.tv/',
        'technologies' => 'WordPress, Elementor, PHP, CSS3, Inbound Marketing',
        'role' => 'Desarrollo Web Full Stack, Diseñador UX/UI, Optimización de Rendimiento',
        'featured_image' => '/images/portfolio/artifices_tv.webp',
        'gallery' => [
            '/images/portfolio/artifices_tv.webp',
        ],
        'results' => [
            'Incremento del 180% en visualizaciones de stream',
            'Diseño 100% responsivo y optimización de carga ultrarrápida',
            'Arquitectura modular para nuevos lanzamientos',
        ],
        'is_featured' => true,
        'order' => 1,
        'meta_title' => 'Artífices TV - Caso de Éxito en Desarrollo Web | REW',
        'meta_description' => 'Diseño y desarrollo web para Artífices TV: plataforma moderna de streaming y conectividad creada por REW.',
    ],
    [
        'title' => 'CODIGO 25',
        'slug' => 'codigo-25',
        'client' => 'CODIGO 25',
        'category' => 'Indumentaria & Vestuario Profesional',
        'project_date' => '2024-04-12',
        'summary' => 'Tienda online de indumentaria corporativa y técnica con pasarelas de pago y logística de envíos integrada.',
        'full_description' => 'Desarrollo de e-commerce en WordPress con WooCommerce y Elementor para CODIGO 25 (codigo25.cl). Implementación de pasarela de pago Transbank Webpay Plus, cotizador dinámico de bordados/estampados y módulo de despachos automatizado según las especificaciones del cliente.',
        'status' => 'Finalizado',
        'project_url' => 'https://codigo25.cl/',
        'technologies' => 'WordPress, WooCommerce, Elementor, Webpay Plus, PHP, CSS3',
        'role' => 'Desarrollo E-Commerce, Integración de Pasarelas y Envíos, Sistema Customizado',
        'featured_image' => '/images/portfolio/codigo_25.webp',
        'gallery' => [
            '/images/portfolio/codigo_25.webp',
        ],
        'results' => [
            'Tasa de conversión superior al 3.8%',
            'Integración de pagos automatizada con Webpay y Transferencia',
        ],
        'is_featured' => true,
        'order' => 2,
        'meta_title' => 'CODIGO 25 - Tienda Online y Branding | REW',
        'meta_description' => 'Desarrollo de e-commerce de alto rendimiento para CODIGO 25.',
    ],
    [
        'title' => 'Cuarteto de Nos (Merch Oficial)',
        'slug' => 'cuarteto-de-nos',
        'client' => 'Cuarteto de Nos / Sotemono Merch',
        'category' => 'E-Commerce Musical',
        'project_date' => '2024-06-10',
        'summary' => 'Tienda online oficial de merchandising internacional para la icónica banda de rock Cuarteto de Nos, con venta global en múltiples divisas.',
        'full_description' => 'Desarrollo de plataforma e-commerce de alto rendimiento para el merchandising oficial de la banda internacional Cuarteto de Nos (gestionado por Sotemono). La tienda fue construida con arquitectura escalable capaz de soportar picos masivos de tráfico durante lanzamientos de giras y álbumes, pasarelas de pago internacionales y nacionales (Webpay Plus, Mercado Pago, PayPal, Stripe), selector de divisas en tiempo real y logística automatizada de despachos internacionales.',
        'status' => 'Finalizado',
        'project_url' => 'https://sotemono.com/cuarteto-de-nos/',
        'technologies' => 'WordPress, WooCommerce, PHP, JavaScript, Webpay Plus, Mercado Pago, Stripe, Cloudflare CDN, Caching de Alto Rendimiento',
        'role' => 'Desarrollo E-Commerce Full Stack, Optimización para Picos de Tráfico, Pasarelas Multi-Moneda, Logística de Despacho',
        'featured_image' => '/images/portfolio/cuarteto_de_nos.webp',
        'gallery' => [
            '/images/portfolio/cuarteto_de_nos.webp',
        ],
        'results' => [
            'Capacidad para soportar más de 25.000 usuarios concurrentes durante aperturas de giras',
            'Reducción del tiempo de checkout a menos de 45 segundos',
            'Venta y despacho automatizado a más de 12 países en Latinoamérica y España',
        ],
        'is_featured' => true,
        'order' => 3,
        'meta_title' => 'Cuarteto de Nos - Tienda Oficial de Merchandising | REW',
        'meta_description' => 'Desarrollo de tienda online para la banda internacional Cuarteto de Nos.',
    ],
    [
        'title' => 'Los Auténticos Decadentes (Merch Oficial)',
        'slug' => 'los-autenticos-decadentes',
        'client' => 'Los Auténticos Decadentes / Sotemono Merch',
        'category' => 'E-Commerce Musical',
        'project_date' => '2024-01-10',
        'summary' => 'Tienda online oficial internacional de merchandising para la legendaria banda argentina Los Auténticos Decadentes.',
        'full_description' => 'Desarrollo de tienda virtual de alta demanda para la gira y merchandising oficial de Los Auténticos Decadentes (sotemono.com). Arquitectura WooCommerce con caché perimetral Cloudflare, pagos multi-divisa (Mercado Pago, PayPal, Stripe) y logística automatizada para despachos masivos.',
        'status' => 'Finalizado',
        'project_url' => 'https://sotemono.com/',
        'technologies' => 'WordPress, WooCommerce, Mercado Pago, PayPal, Stripe, Cloudflare CDN, PHP',
        'role' => 'Desarrollo E-Commerce Internacional, Alta Disponibilidad, Pasarelas de Pago Globales',
        'featured_image' => '/images/portfolio/los_autenticos_decadentes.webp',
        'gallery' => [
            '/images/portfolio/los_autenticos_decadentes.webp',
        ],
        'results' => [
            'Venta masiva de colecciones especiales en giras',
            'Logística automatizada con generación de etiquetas de envío',
        ],
        'is_featured' => true,
        'order' => 4,
        'meta_title' => 'Los Auténticos Decadentes - Tienda Oficial | REW',
        'meta_description' => 'Desarrollo de tienda online oficial para Los Auténticos Decadentes por REW.',
    ],
    [
        'title' => 'JJ Estética',
        'slug' => 'jj-estetica',
        'client' => 'JJ Estética Chile',
        'category' => 'Salud, Belleza & Bienestar',
        'project_date' => '2024-03-25',
        'summary' => 'Sitio web profesional para centro de medicina estética y tratamientos faciales con reserva de horas online.',
        'full_description' => 'Desarrollo web corporativo para JJ Estética (jjestetica.cl). Presentación elegante de catálogo de tratamientos, testimonios, cotizador interactivo y vinculación directa con WhatsApp para agendamiento médico.',
        'status' => 'Finalizado',
        'project_url' => 'https://jjestetica.cl/',
        'technologies' => 'WordPress, Elementor Pro, UI/UX Design, PHP, WhatsApp Business API',
        'role' => 'Diseño y Desarrollo Web, Optimización Mobile, Sistema de Agendamiento Online',
        'featured_image' => '/images/portfolio/jj_estetica.webp',
        'gallery' => [
            '/images/portfolio/jj_estetica.webp',
        ],
        'results' => [
            'Aumento del 120% en solicitudes de evaluación estética',
            'Carga optimizada en dispositivos móviles menores a 1.2s',
        ],
        'is_featured' => true,
        'order' => 5,
        'meta_title' => 'JJ Estética - Sitio Web Corporativo | REW',
        'meta_description' => 'Desarrollo web corporativo para centro de medicina estética JJ Estética.',
    ],
    [
        'title' => 'Sotemono Merch',
        'slug' => 'sotemono',
        'client' => 'Sotemono Merch Chile',
        'category' => 'E-Commerce & Moda',
        'project_date' => '2024-05-01',
        'summary' => 'Plataforma hub matriz de e-commerce y distribución de merchandising para bandas y marcas en Chile.',
        'full_description' => 'Desarrollo de plataforma central de e-commerce para Sotemono (sotemono.com). Gestiona catálogos multi-marca de bandas de rock y artistas urbanos, control centralizado de inventario, pasarelas Webpay Plus, Mercado Pago y despachos globales.',
        'status' => 'Finalizado',
        'project_url' => 'https://sotemono.com/',
        'technologies' => 'WordPress, WooCommerce, Webpay Plus, Mercado Pago, Stripe, PHP',
        'role' => 'Desarrollo E-Commerce Hub, Gestión Multi-Catálogo, Integración Pasarelas',
        'featured_image' => '/images/portfolio/sotemono.webp',
        'gallery' => [
            '/images/portfolio/sotemono.webp',
        ],
        'results' => [
            'Centralización de más de 10 tiendas de merchandising en un solo sistema',
            'Control de inventario unificado para producción y preventa',
        ],
        'is_featured' => true,
        'order' => 6,
        'meta_title' => 'Sotemono Merch - Plataforma E-Commerce | REW',
        'meta_description' => 'Desarrollo de plataforma matriz de e-commerce para Sotemono Merch por REW.',
    ],
    [
        'title' => 'Papel Seda',
        'slug' => 'papel-seda',
        'client' => 'Papel Seda Chile',
        'category' => 'E-Commerce & Packaging',
        'project_date' => '2024-04-10',
        'summary' => 'E-commerce especializado en papel de seda y packaging de calidad con gestión de inventario personalizada y pasarelas de pago.',
        'full_description' => 'Desarrollo de tienda online WooCommerce para Papel Seda (papelseda.cl). Se implementó pasarela de pago Transbank Webpay Plus, sistema de gestión de inventario y pedidos customizado, optimización de velocidad y servicio de soporte y mantenimiento mensual continuo.',
        'status' => 'Finalizado',
        'project_url' => 'https://papelseda.cl/',
        'technologies' => 'WordPress, WooCommerce, PHP, Webpay Plus, JavaScript, Gestión de Inventario a Medida',
        'role' => 'Desarrollo E-Commerce Full Stack, Integración de Pasarelas, Gestión de Inventario Customizada, Mantenimiento Mensual',
        'featured_image' => '/images/portfolio/papel_seda.webp',
        'gallery' => [
            '/images/portfolio/papel_seda.webp',
        ],
        'results' => [
            'Gestión automatizada de pedidos y stock en tiempo real',
            'Soporte técnico mensual y disponibilidad del 99.9%',
        ],
        'is_featured' => true,
        'order' => 7,
        'meta_title' => 'Papel Seda - Tienda E-Commerce y Gestión de Inventario | REW',
        'meta_description' => 'Desarrollo de e-commerce y sistema de inventario a medida para Papel Seda por REW.',
    ],
    [
        'title' => 'Patagonia Shelter',
        'slug' => 'patagonia-shelter',
        'client' => 'Patagonia Shelter Chile',
        'category' => 'Turismo & E-Commerce',
        'project_date' => '2024-03-15',
        'summary' => 'Sitio web corporativo y plataforma de reservas de alojamiento de montaña en la Patagonia elaborado con WordPress y Elementor.',
        'full_description' => 'Sitio web corporativo elaborado con WordPress y Elementor para Patagonia Shelter (patagoniashelter.com). La plataforma integra sistema de reservas en tiempo real para refugios y domos, pasarelas de pago automatizadas en CLP y USD (Webpay Plus, PayPal), mapas interactivos de senderos y optimización SEO para turismo internacional.',
        'status' => 'Finalizado',
        'project_url' => 'https://patagoniashelter.com/',
        'technologies' => 'WordPress, Elementor, WooCommerce, Booking Engine, Webpay Plus, PayPal, JavaScript, SEO Internacional',
        'role' => 'Desarrollo Web Full Stack, Sistema de Reservas, Integración de Pasarelas, SEO Internacional',
        'featured_image' => '/images/portfolio/patagonia_shelter.webp',
        'gallery' => [
            '/images/portfolio/patagonia_shelter.webp',
        ],
        'results' => [
            'Aumento del 210% en reservas directas sin comisiones de OTAs',
            'Carga en menos de 1.4s optimizada para usuarios de todo el mundo',
        ],
        'is_featured' => true,
        'order' => 8,
        'meta_title' => 'Patagonia Shelter - Caso de Éxito en Desarrollo Web | REW',
        'meta_description' => 'Desarrollo de plataforma de reservas y e-commerce turístico para Patagonia Shelter en Chile por REW.',
    ],
    [
        'title' => 'Mercado Patache',
        'slug' => 'mercado-patache',
        'client' => 'Mercado Patache',
        'category' => 'E-Commerce Gourmet',
        'project_date' => '2024-05-12',
        'summary' => 'Tienda online de productos gourmet y alimentos selectos con plataforma WooCommerce propia y campañas de Google & Meta Ads.',
        'full_description' => 'Desarrollo de tienda online WooCommerce propia para Mercado Patache (mercadopatache.com). Incluye catálogo con cálculo de peso y despacho por zonas, integración de pagos online, soporte y mantención técnica mensual continua, junto con gestión estratégica de pauta publicitaria en Google Ads y Meta Ads.',
        'status' => 'Finalizado',
        'project_url' => 'https://mercadopatache.com/',
        'technologies' => 'WordPress, WooCommerce, Google Ads, Meta Ads, Webpay Plus, PHP, CSS3',
        'role' => 'Desarrollo E-Commerce, Integración de Pagos, Mantención Mensual, Estrategia Google Ads & Meta Ads',
        'featured_image' => '/images/portfolio/mercado_patache.webp',
        'gallery' => [
            '/images/portfolio/mercado_patache.webp',
        ],
        'results' => [
            'ROAS de 4.2x en campañas de Google Ads y Meta Ads',
            'Mantención mensual activa sin interrupciones operacionales',
        ],
        'is_featured' => true,
        'order' => 9,
        'meta_title' => 'Mercado Patache - E-Commerce Gourmet y Marketing Digital | REW',
        'meta_description' => 'Desarrollo de tienda WooCommerce propia y pauta digital para Mercado Patache por REW.',
    ],
    [
        'title' => 'Cumbres de Frutillar',
        'slug' => 'cumbres-de-frutillar',
        'client' => 'Cumbres de Frutillar Inmobiliaria',
        'category' => 'Inmobiliaria & Loteos',
        'project_date' => '2024-02-20',
        'summary' => 'Sitio web corporativo inmobiliario con diseño a medida en Elementor y captación de leads mediante Meta Ads y Google Ads.',
        'full_description' => 'Diseño y desarrollo web a medida para el proyecto inmobiliario Cumbres de Frutillar (cumbresdefrutillar.cl) en el sur de Chile. Desarrollado en WordPress con Elementor, integración de planos interactivos de parcelas, formularios de cotización rápida y gestión completa de campañas publicitarias en Meta Ads y Google Ads.',
        'status' => 'Finalizado',
        'project_url' => 'https://cumbresdefrutillar.cl/',
        'technologies' => 'WordPress, Elementor, Meta Ads, Google Ads, UI/UX Design, PHP',
        'role' => 'Diseño UX/UI a Medida, Desarrollo Web, Integración de Leads, Gestión de Pauta Publicitaria Meta & Google Ads',
        'featured_image' => '/images/portfolio/cumbres_de_frutillar.webp',
        'gallery' => [
            '/images/portfolio/cumbres_de_frutillar.webp',
        ],
        'results' => [
            'Más de 450 prospectos calificados captados en el primer trimestre',
            'Diseño visual a medida destacando el entorno natural de Frutillar',
        ],
        'is_featured' => true,
        'order' => 10,
        'meta_title' => 'Cumbres de Frutillar - Diseño Web Inmobiliario y Ads | REW',
        'meta_description' => 'Diseño web a medida y campañas de Google/Meta Ads para Cumbres de Frutillar por REW.',
    ],
    [
        'title' => 'Barrio Bravo (Merch Oficial)',
        'slug' => 'barrio-bravo',
        'client' => 'Barrio Bravo / Sotemono Merch',
        'category' => 'E-Commerce & Cultura',
        'project_date' => '2024-03-01',
        'summary' => 'Tienda online oficial para la comunidad Barrio Bravo con envíos internacionales DHL y pagos multi-divisa.',
        'full_description' => 'Desarrollo de e-commerce WooCommerce customizado para la venta del merchandising y libros oficiales de Barrio Bravo (sotemono.com). Integración de pagos con Mercado Pago y PayPal, conversor de moneda y cálculo automatizado de envíos internacionales con DHL Express.',
        'status' => 'Finalizado',
        'project_url' => 'https://sotemono.com/',
        'technologies' => 'WordPress, WooCommerce, Mercado Pago, PayPal, DHL Express API, PHP, JavaScript',
        'role' => 'Desarrollo E-Commerce Customizado, Integración Mercado Pago & PayPal, Envíos Internacionales DHL',
        'featured_image' => '/images/portfolio/barrio_bravo.webp',
        'gallery' => [
            '/images/portfolio/barrio_bravo.webp',
        ],
        'results' => [
            'Envíos internacionales automatizados a más de 15 países con DHL',
            'Integración de pasarelas locales e internacionales sin fricción',
        ],
        'is_featured' => true,
        'order' => 11,
        'meta_title' => 'Barrio Bravo Merch Oficial - Tienda Online Internacional | REW',
        'meta_description' => 'Desarrollo de tienda WooCommerce con envíos internacionales DHL para Barrio Bravo por REW.',
    ],
    [
        'title' => 'Matías Chinaski (Merch Oficial)',
        'slug' => 'matias-chinaski',
        'client' => 'Matías Chinaski / Sotemono Merch',
        'category' => 'E-Commerce & Música Urbana',
        'project_date' => '2024-04-18',
        'summary' => 'Plataforma de venta oficial de merchandising y música para el destacado artista chileno Matías Chinaski.',
        'full_description' => 'Desarrollo de tienda online WooCommerce customizada para Matías Chinaski (sotemono.com). Soporta lanzamientos de stock limitado (drops), pasarelas de pago Mercado Pago y PayPal, y cálculo de tarifas de courier internacional DHL en tiempo real.',
        'status' => 'Finalizado',
        'project_url' => 'https://sotemono.com/',
        'technologies' => 'WordPress, WooCommerce, Mercado Pago, PayPal, DHL Express, JavaScript, CSS3',
        'role' => 'Desarrollo E-Commerce Customizado, Integración Mercado Pago & PayPal, Envíos Internacionales DHL',
        'featured_image' => '/images/portfolio/matias_chinaski.webp',
        'gallery' => [
            '/images/portfolio/matias_chinaski.webp',
        ],
        'results' => [
            'Agotamiento de drops en menos de 2 horas con tráfico concurrente',
            'Cero fallas en procesamiento de pagos transfronterizos',
        ],
        'is_featured' => true,
        'order' => 12,
        'meta_title' => 'Matías Chinaski Merch Oficial - E-Commerce | REW',
        'meta_description' => 'Tienda WooCommerce personalizada con envíos DHL para Matías Chinaski por REW.',
    ],
    [
        'title' => 'Academiaflix (UDD)',
        'slug' => 'academiaflix',
        'client' => 'Universidad del Desarrollo (UDD) / Academiaflix',
        'category' => 'EdTech & E-Learning',
        'project_date' => '2023-11-15',
        'summary' => 'Plataforma educativa con WooCommerce conectada bidireccionalmente con Salesforce y el sistema integrado de la UDD.',
        'full_description' => 'Desarrollo e integración tecnológica para Academiaflix (academiaflix.rew.cl / UDD). Conexión de catálogo de cursos y suscripciones WooCommerce con Salesforce CRM y APIs institucionales de la Universidad del Desarrollo para sincronización instantánea de alumnos, matrículas y certificados.',
        'status' => 'Finalizado',
        'project_url' => 'https://academiaflix.rew.cl/',
        'technologies' => 'WordPress, WooCommerce, Salesforce REST API, Sistema Integrado UDD, PHP, Webhooks',
        'role' => 'Arquitectura de Software, Conexión WooCommerce + Salesforce, Integración Sistema UDD',
        'featured_image' => '/images/portfolio/academiaflix.webp',
        'gallery' => [
            '/images/portfolio/academiaflix.webp',
        ],
        'results' => [
            'Sincronización automática de matrículas en Salesforce en menos de 3 segundos',
            'Acceso unificado para miles de estudiantes universitarios',
        ],
        'is_featured' => true,
        'order' => 13,
        'meta_title' => 'Academiaflix - Integración WooCommerce, Salesforce y UDD | REW',
        'meta_description' => 'Integración tecnológica de WooCommerce con Salesforce y sistema UDD para Academiaflix por REW.',
    ],
    [
        'title' => 'Otro Día en la Oficina (Modelo Sapiens)',
        'slug' => 'otro-dia-en-la-oficina',
        'client' => 'Modelo Sapiens / Otro Día en la Oficina',
        'category' => 'Desarrollo de Software & Interactividad',
        'project_date' => '2023-08-20',
        'summary' => 'Aplicación web interactiva desarrollada a medida en CodeIgniter con simulación de piano dinámico accionado con el teclado.',
        'full_description' => 'Desarrollo de software y frontend interactivo a medida en CodeIgniter para la obra y propuesta "Otro Día en la Oficina" (otrodiaenlaoficina.cl) de Modelo Sapiens. Incluye sintetizador y piano interactivo accionado mediante las teclas del teclado físico del usuario con animación fluida en Canvas/JavaScript, todo customizado desde la idea que entregó el cliente.',
        'status' => 'Finalizado',
        'project_url' => 'https://otrodiaenlaoficina.cl/',
        'technologies' => 'CodeIgniter (PHP), Web Audio API, JavaScript ES6, HTML5 Canvas, CSS3 Avanzado',
        'role' => 'Desarrollo de Software en CodeIgniter, Programación de Piano Dinámico Interactivo con Teclado, Desarrollo Customizado',
        'featured_image' => '/images/portfolio/otro_dia_en_la_oficina.webp',
        'gallery' => [
            '/images/portfolio/otro_dia_en_la_oficina.webp',
        ],
        'results' => [
            'Experiencia artística sonora 100% interactiva sin dependencias pesadas',
            'Respuesta sonora en tiempo real con latencia inferior a 15ms',
        ],
        'is_featured' => true,
        'order' => 14,
        'meta_title' => 'Otro Día en la Oficina - Software Interactivo CodeIgniter | REW',
        'meta_description' => 'Desarrollo de aplicación web con piano dinámico interactivo en CodeIgniter por REW.',
    ],
];

// Read DatabaseSeeder.php, replace the $projects array with our updated 14 projects
$seederPath = 'c:/laragon/www/rew/database/seeders/DatabaseSeeder.php';
$content = file_get_contents($seederPath);

// Export projects array as PHP code
$projectsCode = var_export($projects, true);

// Regex replace between "$projects = [" and "foreach ($projects as $proj)"
$pattern = '/\$projects\s*=\s*\[.*?\n\s*\];\s*\n\s*foreach\s*\(\$projects/s';
$replacement = "\$projects = {$projectsCode};\n\n        foreach (\$projects";

$newContent = preg_replace($pattern, $replacement, $content);

if ($newContent && $newContent !== $content) {
    file_put_contents($seederPath, $newContent);
    echo "Updated DatabaseSeeder.php successfully with all 14 portfolio projects!\n";
} else {
    echo "Pattern matching failed in DatabaseSeeder.php\n";
}
